name: run start.py
#name: run sub_Status.py

on:
  schedule:
    - cron: '3 * * * MON-FRI' # At 00:03 every hours in weekday
    #- cron: '*/5 * * * *' # every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' # install the python version needed

      - name: install python packages
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run start.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python start.py #sub_Status.py # start.py
        
#      - name: 'Upload Artifact'
#        uses: actions/upload-artifact@v3
#        with:
#          name: my-artifact
#          path: ${{ github.workspace }}

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

#      - name: push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: main
